concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-and-deploy-snapshot:
    if: ${{ github.repository == 'spring-projects/spring-boot' }}
    name: Build and Deploy Snapshot
    outputs:
      version: ${{ steps.build-and-publish.outputs.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check Out Code
      uses: actions/checkout@v4
    - continue-on-error: true
      id: build-and-publish
      name: Build and Publish
      uses: ./.github/actions/build
      with:
        develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
        publish: true
    - continue-on-error: true
      name: Deploy
      uses: spring-io/artifactory-deploy-action@26bbe925a75f4f863e1e529e85be2d0093cac116
      with:
        build-name: spring-boot-3.4.x
        folder: deployment-repository
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        repository: libs-snapshot-local
        signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
        signing-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        uri: https://repo.spring.io
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
    - continue-on-error: true
      if: always()
      name: Send Notification
      uses: ./.github/actions/send-notification
      with:
        build-scan-url: ${{ steps.build-and-publish.outputs.build-scan-url }}
        run-name: ${{ format('{0} | Linux | Java 17', github.ref_name) }}
        status: ${{ job.status }}
        webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
  trigger-docs-build:
    name: Trigger Docs Build
    needs: build-and-deploy-snapshot
    permissions:
      actions: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Run Deploy Docs Workflow
      run: gh workflow run deploy-docs.yml --repo spring-projects/spring-boot -r docs-build
        -f build-refname=${{ github.ref_name }} -f build-version=${{ needs.build-and-deploy-snapshot.outputs.version
        }}
  verify:
    name: Verify
    needs: build-and-deploy-snapshot
    secrets:
      google-chat-webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
      repository-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      repository-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
    uses: ./.github/workflows/verify.yml
    with:
      version: ${{ needs.build-and-deploy-snapshot.outputs.version }}
name: Build and Deploy Snapshot
on:
  repository_dispatch:
    types: trigger-ga___build-and-deploy-snapshot.yml
