concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    if: ${{ github.repository == 'spring-projects/spring-boot' }}
    name: ${{ matrix.os.name}} | Java ${{ matrix.java.version}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ runner.os == 'Windows' }}
      name: Prepare Windows runner
      run: 'git config --global core.autocrlf true

        git config --global core.longPaths true

        Stop-Service -name Docker

        '
    - continue-on-error: true
      name: Check Out Code
      uses: actions/checkout@v4
    - continue-on-error: true
      id: build
      name: Build
      uses: ./.github/actions/build
      with:
        develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
        java-distribution: ${{ matrix.java.distribution || 'liberica' }}
        java-toolchain: ${{ matrix.java.toolchain }}
        java-version: ${{ matrix.java.version }}
    - continue-on-error: true
      if: always()
      name: Send Notification
      uses: ./.github/actions/send-notification
      with:
        build-scan-url: ${{ steps.build.outputs.build-scan-url }}
        run-name: ${{ format('{0} | {1} | Java {2}', github.ref_name, matrix.os.name,
          matrix.java.version) }}
        status: ${{ job.status }}
        webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
    strategy:
      matrix:
        exclude:
        - java:
            version: 17
          os:
            name: Linux
        java:
        - toolchain: false
          version: 17
        - toolchain: true
          version: 21
        - toolchain: true
          version: 22
        os:
        - id: ubuntu-latest
          name: Linux
        - id: windows-latest
          name: Windows
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
