concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-and-stage-release:
    if: ${{ github.repository == 'spring-projects/spring-boot' }}
    name: Build and Stage Release
    outputs:
      version: ${{ steps.build-and-publish.outputs.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check Out Code
      uses: actions/checkout@v4
    - continue-on-error: true
      id: build-and-publish
      name: Build and Publish
      uses: ./.github/actions/build
      with:
        develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
        publish: true
    - continue-on-error: true
      name: Stage Release
      uses: spring-io/artifactory-deploy-action@26bbe925a75f4f863e1e529e85be2d0093cac116
      with:
        build-name: ${{ format('spring-boot-{0}', steps.build-and-publish.outputs.version)}}
        folder: deployment-repository
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        repository: libs-staging-local
        signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
        signing-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        uri: https://repo.spring.io
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
  create-github-release:
    name: Create GitHub Release
    needs:
    - build-and-stage-release
    - promote-release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check Out Code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      name: Create GitHub Release
      uses: ./.github/actions/create-github-release
      with:
        milestone: ${{ needs.build-and-stage-release.outputs.version }}
        pre-release: true
        token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
  promote-release:
    name: Promote Release
    needs:
    - build-and-stage-release
    - verify
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@8bab65dc312163b065ac5b03de6f6a5bdd1bec41
    - continue-on-error: true
      name: Promote build
      run: jfrog rt build-promote ${{ format('spring-boot-{0}', needs.build-and-stage-release.outputs.version)}}
        ${{ github.run_number }} libs-milestone-local
  verify:
    name: Verify
    needs: build-and-stage-release
    secrets:
      google-chat-webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
      repository-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      repository-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
    uses: ./.github/workflows/verify.yml
    with:
      staging: true
      version: ${{ needs.build-and-stage-release.outputs.version }}
name: Release Milestone
on:
  repository_dispatch:
    types: trigger-ga___release-milestone.yml
