concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  run-system-tests:
    if: ${{ github.repository == 'spring-projects/spring-boot' }}
    name: Java ${{ matrix.java.version}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check Out Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Prepare Gradle Build
      uses: ./.github/actions/prepare-gradle-build
      with:
        develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
        java-toolchain: ${{ matrix.java.toolchain }}
        java-version: ${{ matrix.java.version }}
    - continue-on-error: true
      id: run-system-tests
      name: Run System Tests
      run: ./gradlew systemTest
      shell: bash
    - continue-on-error: true
      if: always()
      name: Send Notification
      uses: ./.github/actions/send-notification
      with:
        build-scan-url: ${{ steps.run-system-tests.outputs.build-scan-url }}
        run-name: ${{ format('{0} | System Tests | Java {1}', github.ref_name, matrix.java.version)
          }}
        status: ${{ job.status }}
        webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
    strategy:
      matrix:
        java:
        - toolchain: false
          version: 17
        - toolchain: true
          version: 21
name: Run System Tests
on:
  repository_dispatch:
    types: trigger-ga___run-system-tests.yml
