jobs:
  trigger-docs-build:
    if: github.repository_owner == 'spring-projects'
    name: Trigger Docs Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check Out
      uses: actions/checkout@v4
      with:
        ref: docs-build
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Trigger Workflow
      run: gh workflow run deploy-docs.yml -r docs-build -f build-refname=${{ github.event.inputs.build-refname
        }} -f build-version=${{ github.event.inputs.build-version }}
name: Trigger Docs Build
on:
  repository_dispatch:
    types: trigger-ga___trigger-docs-build.yml
permissions:
  actions: write
