jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: gradle/actions/wrapper-validation@d9c87d481d55275bb5441eef3fe0e46805f9ef70
name: Validate Gradle Wrapper
on:
  repository_dispatch:
    types: trigger-ga___validate-gradle-wrapper.yml
permissions:
  contents: read
